### ISSUE TITLE
SpringCloud samples POM内定义的版本号引发AOP代理导致的ClassLoader错误问题。

### ISSUE THREAD

**Issue by whalezhao** [koupleless/samples#10]
问题描述：
SpringCloud samples 内参阅版本为<spring-cloud.version>2021.0.8</spring-cloud.version>
该版本对应的Springboot 版本为2.6.15，
该springboot 内的Spring-context 版本为 5.3.27
错误原因：
该版本下的JdkDynamicAopProxy  会有一段代码导致模块Classloader 进行错误指定。
对应截图
<img width="722" alt="1711613747111_2EB280D9-1FB1-4a15-8BB1-A4B4A8610F1C" src="https://github.com/koupleless/samples/assets/49772101/80a3b54f-320c-4861-9886-204ce2d6ef2c">
备：
 5.3.26 版本下的Spring-context 则没有该问题。

**Comment by lvjing2** [comment]
你好，我们会在这个 PR 里修复
https://github.com/koupleless/koupleless/issues/244

**Comment by lvjing2** [comment]
已修复
